export const CANONICAL_PERMISSIONS = {
  "users:create:any": "Membuat user mana pun",
  "users:read:any": "Membaca semua user",
  "users:read:own": "Membaca user sendiri",
  "users:update:any": "Mengubah semua user",
  "users:update:own": "Mengubah user sendiri",
  "users:delete:any": "Menghapus semua user",
  "users:delete:own": "Menghapus user sendiri",
  "roles:read:any": "Membaca semua role",
  "roles:read:own": "Membaca role sendiri",
  "roles:update:any": "Mengubah semua role",
  "investors:create:any": "Membuat profil investor untuk user mana pun",
  "investors:create:own": "Membuat profil investor sendiri",
  "investors:read:any": "Membaca semua investor",
  "investors:read:own": "Membaca profil investor sendiri",
  "investors:update:any": "Mengubah semua investor",
  "investors:update:own": "Mengubah profil investor sendiri",
  "investors:delete:any": "Menghapus semua investor",
  "investors:delete:own": "Menghapus profil investor sendiri",
  "investor_documents:upload:any": "Mengunggah dokumen untuk semua investor",
  "investor_documents:upload:own": "Mengunggah dokumen investor sendiri",
  "investor_documents:download:any": "Mengunduh semua dokumen investor",
  "investor_documents:download:own": "Mengunduh dokumen investor sendiri",
  "investor_documents:delete:any": "Menghapus semua dokumen investor",
  "investor_documents:delete:own": "Menghapus dokumen investor sendiri",
  "companies:create:any": "Membuat perusahaan",
  "companies:read:any": "Membaca semua perusahaan",
  "companies:update:any": "Mengubah perusahaan",
  "companies:delete:any": "Menghapus perusahaan",
  "company_documents:upload:any": "Mengunggah dokumen perusahaan",
  "company_documents:read:any": "Membaca metadata dokumen perusahaan",
  "company_documents:update:any": "Mengubah metadata dokumen perusahaan",
  "company_documents:download:any": "Mengunduh dokumen perusahaan",
  "company_documents:delete:any": "Menghapus dokumen perusahaan",
  "projects:create:any": "Membuat project",
  "projects:read:any": "Membaca semua project",
  "projects:update:any": "Mengubah project",
  "projects:delete:any": "Menghapus project",
  "project_documents:upload:any": "Mengunggah dokumen project",
  "project_documents:read:any": "Membaca metadata dokumen project",
  "project_documents:update:any": "Mengubah metadata dokumen project",
  "project_documents:download:any": "Mengunduh dokumen project",
  "project_documents:delete:any": "Menghapus dokumen project",
} as const;

const OWN_PERMISSIONS = [
  "users:read:own",
  "users:update:own",
  "users:delete:own",
  "roles:read:own",
  "investors:create:own",
  "investors:read:own",
  "investors:update:own",
  "investors:delete:own",
  "investor_documents:upload:own",
  "investor_documents:download:own",
  "investor_documents:delete:own",
] as const;

const ADMIN_PERMISSIONS = [
  "users:create:any",
  "users:read:any",
  "users:update:any",
  "users:delete:any",
  "roles:read:any",
  "investors:create:any",
  "investors:read:any",
  "investors:update:any",
  "investors:delete:any",
  "investor_documents:upload:any",
  "investor_documents:download:any",
  "investor_documents:delete:any",
  "companies:create:any",
  "companies:read:any",
  "companies:update:any",
  "companies:delete:any",
  "company_documents:upload:any",
  "company_documents:read:any",
  "company_documents:update:any",
  "company_documents:download:any",
  "company_documents:delete:any",
  "projects:create:any",
  "projects:read:any",
  "projects:update:any",
  "projects:delete:any",
  "project_documents:upload:any",
  "project_documents:read:any",
  "project_documents:update:any",
  "project_documents:download:any",
  "project_documents:delete:any",
] as const;

export const CANONICAL_ROLE_PERMISSIONS = {
  user: OWN_PERMISSIONS,
  investor: OWN_PERMISSIONS,
  admin: [...ADMIN_PERMISSIONS, "roles:update:any"],
  superadmin: [...ADMIN_PERMISSIONS, "roles:update:any"],
  bod: [
    "users:read:any",
    "roles:read:any",
    "investors:read:any",
    "investor_documents:download:any",
    "companies:read:any",
    "company_documents:read:any",
    "company_documents:download:any",
    "projects:read:any",
    "project_documents:read:any",
    "project_documents:download:any",
  ],
} as const;
