-- AlterEnum
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_CREATE';
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_UPDATE';
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_DELETE';
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_DOCUMENT_UPLOAD';
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_DOCUMENT_UPDATE';
ALTER TYPE "ActivityAction" ADD VALUE 'PROJECT_DOCUMENT_DELETE';
