ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PERMISSION_CREATE';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PERMISSION_UPDATE';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PERMISSION_DELETE';
